(test
 (name sprite_test)
 (modules sprite_test)
 (libraries vdpcore))

(test
 (name keyboard_test)
 (modules keyboard_test)
 (libraries msx))

(test
 (name g2_test)
 (modules g2_test)
 (libraries vdpcore))

(test
 (name mode_test)
 (modules mode_test)
 (libraries msx))

(test
 (name replay_test)
 (modules replay_test)
 (libraries msx))

(test
 (name mapper_test)
 (modules mapper_test)
 (libraries msx))

(test
 (name palette_test)
 (modules palette_test)
 (libraries msx))

(test
 (name disk_test)
 (modules disk_test)
 (libraries msx))

(test
 (name bitmap_test)
 (modules bitmap_test)
 (libraries vdpcore))

(test
 (name state_test)
 (modules state_test)
 (libraries msx))

(test
 (name fat12_write_test)
 (modules fat12_write_test)
 (libraries msx))

(test
 (name vdp_line_test)
 (modules vdp_line_test)
 (libraries msx))
